-- Create history tables
CREATE TABLE IF NOT EXISTS `civicrm_contacthistory_address` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Address ID',
  `original_id` int unsigned COMMENT 'Original address ID from civicrm_address',
  `contact_id` int unsigned COMMENT 'FK to Contact ID',
  `location_type_id` int unsigned COMMENT 'Which Location does this address belong to.',
  `is_primary` tinyint DEFAULT 0 COMMENT 'Is this the primary address.',
  `is_billing` tinyint DEFAULT 0 COMMENT 'Is this the billing address.',
  `street_address` varchar(96) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Concatenation of all routable street address components.',
  `street_number` int DEFAULT NULL COMMENT 'Numeric portion of address number on the street.',
  `street_number_suffix` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Non-numeric portion of address number.',
  `street_number_predirectional` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Directional prefix.',
  `street_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Actual street name.',
  `street_type` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'St, Rd, Dr, etc.',
  `street_number_postdirectional` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Directional suffix.',
  `street_unit` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Secondary unit designator.',
  `supplemental_address_1` varchar(96) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Supplemental Address Information, Line 1',
  `supplemental_address_2` varchar(96) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Supplemental Address Information, Line 2',
  `supplemental_address_3` varchar(96) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Supplemental Address Information, Line 3',
  `city` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'City, Town or Village name.',
  `county_id` int unsigned DEFAULT NULL COMMENT 'Which County does this address belong to.',
  `state_province_id` int unsigned DEFAULT NULL COMMENT 'Which State_Province does this address belong to.',
  `postal_code_suffix` varchar(12) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Store the suffix, like the +4 part in the USPS system.',
  `postal_code` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Store both US (zip5) AND international postal codes.',
  `usps_adr_dp` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'USPS Bulk mailing code.',
  `country_id` int unsigned DEFAULT NULL COMMENT 'Which Country does this address belong to.',
  `geo_code_1` double DEFAULT NULL COMMENT 'Latitude',
  `geo_code_2` double DEFAULT NULL COMMENT 'Longitude',
  `manual_geo_code` tinyint DEFAULT 0 COMMENT 'Is this a manually entered geo code',
  `timezone` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Timezone expressed as a UTC offset.',
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Name of the location',
  `master_id` int unsigned DEFAULT NULL COMMENT 'Saved address belongs to which contact',
  `start_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When this history record was created',
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When this history record was last modified',
  `end_date` timestamp NULL DEFAULT NULL COMMENT 'When this address was deleted/replaced',
  PRIMARY KEY (`id`),
  KEY `index_original_id` (`original_id`),
  KEY `index_contact_id` (`contact_id`),
  KEY `index_location_type` (`location_type_id`),
  KEY `index_is_primary` (`is_primary`),
  KEY `index_is_billing` (`is_billing`),
  KEY `index_street_name` (`street_name`),
  KEY `index_city` (`city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `civicrm_contacthistory_email` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Email ID',
  `original_id` int unsigned COMMENT 'Original email ID from civicrm_email',
  `contact_id` int unsigned COMMENT 'FK to Contact ID',
  `location_type_id` int unsigned COMMENT 'Which Location does this email belong to.',
  `email` varchar(254) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Email address',
  `is_primary` tinyint DEFAULT 0 COMMENT 'Is this the primary email for this contact and location.',
  `is_billing` tinyint DEFAULT 0 COMMENT 'Is this the billing email for this contact and location.',
  `on_hold` int unsigned NOT NULL DEFAULT 0 COMMENT 'Is this address on bounce hold (for mailings)',
  `is_bulkmail` tinyint DEFAULT 0 COMMENT 'Is this address for bulk mail ?',
  `hold_date` datetime DEFAULT NULL COMMENT 'When the address went on bounce hold',
  `reset_date` datetime DEFAULT NULL COMMENT 'When the address bounce status was last reset',
  `signature_text` text COLLATE utf8_unicode_ci COMMENT 'Text formatted signature for the email.',
  `signature_html` text COLLATE utf8_unicode_ci COMMENT 'HTML formatted signature for the email.',
  `start_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When this history record was created',
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When this history record was last modified',
  `end_date` timestamp NULL DEFAULT NULL COMMENT 'When this email was deleted/replaced',
  PRIMARY KEY (`id`),
  KEY `index_original_id` (`original_id`),
  KEY `index_contact_id` (`contact_id`),
  KEY `index_location_type` (`location_type_id`),
  KEY `index_email` (`email`),
  KEY `index_is_primary` (`is_primary`),
  KEY `index_is_billing` (`is_billing`),
  KEY `index_on_hold` (`on_hold`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `civicrm_contacthistory_phone` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Phone ID',
  `original_id` int unsigned COMMENT 'Original phone ID from civicrm_phone',
  `contact_id` int unsigned COMMENT 'FK to Contact ID',
  `location_type_id` int unsigned COMMENT 'Which Location does this phone belong to.',
  `is_primary` tinyint DEFAULT 0 COMMENT 'Is this the primary phone for this contact and location.',
  `is_billing` tinyint DEFAULT 0 COMMENT 'Is this the billing phone for this contact and location.',
  `mobile_provider_id` int unsigned DEFAULT NULL COMMENT 'Which Mobile Provider does this phone belong to.',
  `phone` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Complete phone number.',
  `phone_ext` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Optional extension for a phone number.',
  `phone_numeric` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Phone Phone number stripped of all whitespace, letters, and punctuation.',
  `phone_type_id` int unsigned DEFAULT NULL COMMENT 'Which type of phone does this number belongs.',
  `start_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When this history record was created',
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When this history record was last modified',
  `end_date` timestamp NULL DEFAULT NULL COMMENT 'When this phone was deleted/replaced',
  PRIMARY KEY (`id`),
  KEY `index_original_id` (`original_id`),
  KEY `index_contact_id` (`contact_id`),
  KEY `index_location_type` (`location_type_id`),
  KEY `index_is_primary` (`is_primary`),
  KEY `index_is_billing` (`is_billing`),
  KEY `index_phone_numeric` (`phone_numeric`),
  KEY `index_phone_type_id` (`phone_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

